=== VertusCZ/2024_philips_hue_app/backend/configure-schema-old.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "hueBridge": {
      "type": "object",
      "properties": {
        "ipAddress": {
          "type": "string",
          "format": "ipv4"
        },
        "username": {
          "type": "string"
        }
      },
      "required": ["ipAddress", "username"]
    },
    "externalApis": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string",
            "format": "uri"
          },
          "pollingInterval": {
            "type": "integer"
          },
          "dataType": {
            "type": "string",
            "enum": ["json"]
          }
        },
        "required": ["name", "url", "dataType"]
      }
    },
    "inputData": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "dataMapping": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          }
        }
      }
    },
    "automationRules": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "trigger": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": ["externalData", "time"]
              },
              "apiName": {
                "type": "string"
              },
              "key": {
                "type": "string"
              },
              "condition": {
                "type": "string",
                "enum": ["equals", "notEquals", "greaterThan", "lessThan"]
              },
              "value": {
                "type": ["string", "number"]
              },
              "timeWindow": {
                "type": "object",
                "properties": {
                  "inCurrentTime": {
                    "type": "boolean"
                  },
                  "timeLimit": {
                    "type": "integer"
                  }
                },
                "required": ["inCurrentTime", "timeLimit"]
              }
            },
            "required": ["type", "condition", "value"]
          },
          "action": {
            "type": "object",
            "properties": {
              "deviceType": {
                "type": "string",
                "enum": ["light", "plug"]
              },
              "deviceId": {
                "type": "string"
              },
              "state": {
                "type": "object",
                "properties": {
                  "on": {
                    "type": "boolean"
                  },
                  "bri": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 255
                  },
                  "hue": {
                    "type": "integer"
                  }
                },
                "required": ["on"]
              }
            },
            "required": ["deviceType", "deviceId", "state"]
          }
        },
        "required": ["id", "trigger", "action"]
      }
    },
    "groups": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "localTime": {
            "type": "string",
            "format": "date-time"
          },
          "devices": {
            "type": "object",
            "properties": {
              "lights": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "plugs": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          },
          "type": {
            "type": "string"
          }
        },
        "required": ["name", "localTime"]
      }
    }
  },
  "required": ["hueBridge", "externalApis", "inputData", "automationRules", "groups"]
}

=== VertusCZ/2024_philips_hue_app/backend/zaloha.json
{
  "hueBridge": {
    "ipAddress": "192.168.1.2",
    "username": "7IXh-UlA6VQ0cutRjQb6wDI1USYa7iXHZfVwKj0l"
  },
  "externalApis": [
    {
      "name": "WeatherApi",
      "url": "https://api.openweathermap.org/data/2.5/weather?q=Ostrava&appid=2c8ce0f495b381164aba7730836722b6",
      "pollingInterval": 7000,
      "dataType": "json"
    },
    {
      "name": "CurrencyApi",
      "url": "https://api.currencyapi.com/v3/latest?apikey=cur_live_zyTosi4xhLCyQMMIrRl4rk3HXBOpTtnFz7MmvEwb&currencies=EUR%2CUSD%2CCAD&base_currency=CZK",
      "pollingInterval": 9000,
      "dataType": "json"
    }
  ],
  "inputData": {
    "WeatherApi": {
      "dataMapping": {
        "weatherCondition": "weather[0].main"
      }
    },
    "CurrencyApi": {
      "dataMapping": {
        "exchangeRate": "data.EUR.value"
      }
    }
  },
  "automationRules": [
    {
      "id": "1",
      "trigger": {
        "type": "externalData",
        "apiName": "WeatherApi",
        "key": "weatherCondition",
        "condition": "equals",
        "value": "Clouds",
        "timeWindow": {
          "inCurrentTime": true,
          "timeLimit": 120000
        }
      },
      "action": {
        "deviceType": "light",
        "deviceId": "1",
        "state": {
          "on": true,
          "bri": 90,
          "hue": 46920
        }
      }
    },
    {
      "id": "2",
      "trigger": {
        "type": "externalData",
        "apiName": "CurrencyApi",
        "key": "exchangeRate",
        "condition": "lessThan",
        "value": "0.05"
      },
      "action": {
        "deviceType": "plug",
        "deviceId": "2",
        "state": {
          "on": true
        }
      }
    }
  ],
  "groups": {
    "1": {
      "name": "Bakalarka",
      "localTime": "2023-11-25T13:13:37",
      "devices": {
        "lights": ["1", "2"],
        "plugs": ["3"]
      },
      "type": "room"
    },
    "2": {
      "name": "Bakalarka 2",
      "localTime": "2023-11-25T13:13:37",
      "devices": {
        "lights": ["4"]
      },
      "type": "living room"
    }
  }
}
